# fly.toml app configuration file generated for ternlang-api on 2026-04-04T06:28:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ternlang-api'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
